# Generated by Django 5.1.7 on 2025-03-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=10, unique=True, verbose_name="Инвайт-код")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=15, unique=True, verbose_name="Номер телефона")),
                ("invite_code", models.CharField(max_length=10, unique=True, verbose_name="Инвайт-код")),
            ],
        ),
    ]
